export interface ContentItem {
  id: string
  title: string
  synopsis: string
  genre: string[]
  year: number
  duration: string
  rating: string
  category: 'Filme' | 'Série'
  language: string
  posterColor: string
  accentColor: string
  episode?: string
  progress?: number
  timeLeft?: string
  matchScore?: number
  matchReason?: string
  isNew?: boolean
  cast?: string[]
}

export const featuredContent: ContentItem[] = [
  {
    id: 'nebula-norte',
    title: 'Nebula Norte',
    synopsis:
      'Uma tripulação isolada descobre sinais de uma civilização perdida nos limites do sistema solar.',
    genre: ['Ficção Científica', 'Aventura'],
    year: 2024,
    duration: '2h 14min',
    rating: '14+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a2a3a',
    accentColor: '#4a8fa8',
    cast: ['Marina Luz', 'André Castelo', 'Priya Nair', 'Lucas Vaz'],
  },
  {
    id: 'cidade-de-vidro',
    title: 'Cidade de Vidro',
    synopsis:
      'Em uma metrópole onde memórias podem ser compradas, uma investigadora procura a verdade sobre o próprio passado.',
    genre: ['Thriller', 'Ficção Científica'],
    year: 2024,
    duration: '8 episódios',
    rating: '16+',
    category: 'Série',
    language: 'Português',
    posterColor: '#2a1a3a',
    accentColor: '#8a4aaa',
    cast: ['Carla Monte', 'Rodrigo Sal', 'Beatriz Faro'],
  },
  {
    id: 'ultimo-verao',
    title: 'O Último Verão Azul',
    synopsis:
      'Três amigos retornam à cidade natal e encontram uma história inacabada que mudará suas vidas para sempre.',
    genre: ['Drama', 'Romance'],
    year: 2024,
    duration: '1h 52min',
    rating: '12+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a3a2a',
    accentColor: '#4aaa6a',
    cast: ['Sofia Belo', 'Tiago Mar', 'Ana Flor'],
  },
]

export const continueWatching: ContentItem[] = [
  {
    id: 'nebula-norte-cw',
    title: 'Nebula Norte',
    synopsis: 'Uma tripulação isolada descobre sinais de uma civilização perdida.',
    genre: ['Ficção Científica'],
    year: 2024,
    duration: '2h 14min',
    rating: '14+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a2a3a',
    accentColor: '#4a8fa8',
    progress: 62,
    timeLeft: '48 min restantes',
  },
  {
    id: 'arquivo-sombras',
    title: 'Arquivo Sombras',
    synopsis: 'Um detetive mergulha nos arquivos mais obscuros de uma cidade.',
    genre: ['Crime', 'Drama'],
    year: 2023,
    duration: '6 episódios',
    rating: '16+',
    category: 'Série',
    language: 'Português',
    posterColor: '#2a1a1a',
    accentColor: '#aa4a4a',
    episode: 'T1:E4',
    progress: 35,
    timeLeft: '38 min restantes',
  },
  {
    id: 'mare-alta',
    title: 'Maré Alta',
    synopsis: 'Uma família enfrenta segredos profundos no litoral.',
    genre: ['Drama', 'Suspense'],
    year: 2024,
    duration: '5 episódios',
    rating: '12+',
    category: 'Série',
    language: 'Português',
    posterColor: '#1a2a3a',
    accentColor: '#4a6aaa',
    episode: 'T2:E2',
    progress: 78,
    timeLeft: '22 min restantes',
  },
  {
    id: 'codigo-aurora',
    title: 'Código Aurora',
    synopsis: 'A corrida contra o tempo para decifrar um código que pode mudar tudo.',
    genre: ['Ação', 'Thriller'],
    year: 2024,
    duration: '2h 05min',
    rating: '14+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#3a2a1a',
    accentColor: '#aa6a4a',
    progress: 15,
    timeLeft: '1h 45min restantes',
  },
]

export const newReleases: ContentItem[] = [
  {
    id: 'distrito-11',
    title: 'Distrito 11',
    synopsis: 'Em um futuro próximo, um bairro se levanta contra um sistema opressor.',
    genre: ['Ação', 'Drama'],
    year: 2025,
    duration: '2h 08min',
    rating: '16+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#2a1a1a',
    accentColor: '#cc4a4a',
    isNew: true,
  },
  {
    id: 'vozes-amanha',
    title: 'Vozes do Amanhã',
    synopsis: 'Um grupo de jovens descobre que suas vozes têm poder de mudar o futuro.',
    genre: ['Ficção', 'Aventura'],
    year: 2025,
    duration: '10 episódios',
    rating: '12+',
    category: 'Série',
    language: 'Português',
    posterColor: '#1a3a3a',
    accentColor: '#4aaaaa',
    isNew: true,
  },
  {
    id: 'linha-final',
    title: 'Linha Final',
    synopsis: 'A última corrida de um piloto lendário que esconde um segredo devastador.',
    genre: ['Drama', 'Esporte'],
    year: 2025,
    duration: '1h 58min',
    rating: '12+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a1a2a',
    accentColor: '#4a4aaa',
    isNew: true,
  },
  {
    id: 'casa-atlas',
    title: 'Casa Atlas',
    synopsis: 'Uma arquiteta descobre que sua casa mais famosa guarda um segredo antigo.',
    genre: ['Mistério', 'Drama'],
    year: 2025,
    duration: '6 episódios',
    rating: '14+',
    category: 'Série',
    language: 'Português',
    posterColor: '#2a2a1a',
    accentColor: '#aaaa4a',
    isNew: true,
  },
  {
    id: 'mapa-invisivel',
    title: 'O Mapa Invisível',
    synopsis: 'Um cartógrafo encontra um mapa que leva a lugares que não deveriam existir.',
    genre: ['Fantasia', 'Aventura'],
    year: 2025,
    duration: '2h 22min',
    rating: '10+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a3a2a',
    accentColor: '#4aaa6a',
    isNew: true,
  },
  {
    id: 'fragmentos',
    title: 'Fragmentos',
    synopsis: 'Cinco estranhos acordam sem memórias, conectados por um evento misterioso.',
    genre: ['Suspense', 'Ficção'],
    year: 2025,
    duration: '8 episódios',
    rating: '16+',
    category: 'Série',
    language: 'Português',
    posterColor: '#2a1a3a',
    accentColor: '#8a4aaa',
    isNew: true,
  },
]

export const recommended: ContentItem[] = [
  {
    id: 'aurora-9',
    title: 'Aurora 9',
    synopsis: 'A nona missão espacial da humanidade enfrenta o inesperado.',
    genre: ['Ficção Científica', 'Aventura'],
    year: 2023,
    duration: '2h 30min',
    rating: '14+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#1a2a3a',
    accentColor: '#4a8faa',
    matchScore: 97,
    matchReason: 'Porque você assistiu Nebula Norte',
  },
  {
    id: 'sol-de-inverno',
    title: 'Sol de Inverno',
    synopsis: 'Uma jornalista investiga a morte de um político em uma cidade fria e isolada.',
    genre: ['Thriller', 'Drama'],
    year: 2023,
    duration: '7 episódios',
    rating: '16+',
    category: 'Série',
    language: 'Português',
    posterColor: '#1a2a3a',
    accentColor: '#6a8aaa',
    matchScore: 94,
    matchReason: 'Porque você curtiu Arquivo Sombras',
  },
  {
    id: 'ponto-cego',
    title: 'Ponto Cego',
    synopsis: 'Um motorista descobre que pode ver o futuro nos espelhos retrovisores.',
    genre: ['Thriller', 'Mistério'],
    year: 2024,
    duration: '1h 46min',
    rating: '14+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#2a2a1a',
    accentColor: '#aaaa4a',
    matchScore: 91,
    matchReason: 'Baseado no seu histórico',
  },
  {
    id: 'horas-claras',
    title: 'As Horas Claras',
    synopsis: 'Um romance delicado sobre tempo, perda e o que fica entre os momentos.',
    genre: ['Drama', 'Romance'],
    year: 2024,
    duration: '1h 55min',
    rating: '12+',
    category: 'Filme',
    language: 'Português',
    posterColor: '#3a2a1a',
    accentColor: '#aa8a4a',
    matchScore: 88,
    matchReason: 'Porque você assistiu O Último Verão Azul',
  },
  {
    id: 'depois-meia-noite',
    title: 'Depois da Meia-Noite',
    synopsis: 'Uma cidade que só existe à noite guarda os segredos de quem a habita.',
    genre: ['Fantasia', 'Drama'],
    year: 2024,
    duration: '9 episódios',
    rating: '14+',
    category: 'Série',
    language: 'Português',
    posterColor: '#1a1a2a',
    accentColor: '#4a4aaa',
    matchScore: 85,
    matchReason: 'Porque você curtiu Cidade de Vidro',
  },
  {
    id: 'circulo-aberto',
    title: 'Círculo Aberto',
    synopsis: 'Um grupo de artistas descobre que suas obras estão conectadas por um mistério.',
    genre: ['Mistério', 'Drama'],
    year: 2024,
    duration: '6 episódios',
    rating: '14+',
    category: 'Série',
    language: 'Português',
    posterColor: '#2a1a2a',
    accentColor: '#aa4aaa',
    matchScore: 82,
    matchReason: 'Tendência na sua região',
  },
]

export const profiles = [
  {
    id: 'p1',
    name: 'Marina',
    initials: 'MA',
    color: '#4a8fa8',
    tag: 'Ficção & Aventura',
  },
  {
    id: 'p2',
    name: 'Rafael',
    initials: 'RF',
    color: '#aa4a4a',
    tag: 'Ação & Thriller',
  },
  {
    id: 'p3',
    name: 'Lucia',
    initials: 'LC',
    color: '#4aaa6a',
    tag: 'Drama & Romance',
  },
  {
    id: 'p4',
    name: 'Infantil',
    initials: 'INF',
    color: '#aaaa4a',
    tag: 'Animação',
  },
]
